### ISSUE TITLE
Question about EnvRunner: multiple environments but one buffer

### ISSUE THREAD

**Issue by telejesus2** [stepjam/YARR#1]
Hi, 
Thanks a ton for sharing your amazing framework.

I have one question regarding the EnvRunner class. I apologize if I misunderstood something and the question is not relevant. 

The EnvRunner class allows multiple processes to collect samples in separate training environments, but they all seem to add their samples to the same replay buffer. Doesn't this cause a problem when we sample from this buffer (contiguous samples in the buffer are no longer sequentially tied)?

Thanks!

**Comment by stepjam** [comment]
Hi,
No problem, hope you find it useful.
Yes, the EnvRunner allows multiple processes to collect samples and add to a unified buffer. Each process keeps the current trajectory local until it is completed, and only then inserts it into the shared buffer (via a global lock), so this ensure samples are contiguous.
